edgi-govdata-archiving/web-monitoring-db

.rubocop.yml
.rubocop_todo.yml
app/models/page.rb
app/models/version.rb
db/migrate/20170425211418_add_missing_page_schemes.rb
db/schema.rb
test/models/page_test.rb

Fixes #25 and ensures that pages always have absolute URLs.
- If they are missing a scheme, it adds `https://`
- If they are missing a domain and TLD, they are marked as invalid so the page can’t be saved
This also adds a migration that fixes up existing page records.

Normalize page URLs

---

README.md

Our license text was a little out of date. We now match https://github.com/edgi-govdata-archiving/overview/blob/master/PROJECT.md#license--copyright-readme-block

Update README to match EDGI standard

---

db/migrate/20170313192244_create_new_db_schema_with_generic_page_version_change_annotation.rb

Not sure how this happened; I think I rebuilt the DB at some point for staging, so may have somehow skipped this migration.

Fix totally borked migration for Heroku

---

.rubocop.yml
app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/versions_controller.rb
app/controllers/concerns/paging_concern.rb
app/models/application_record.rb
config/routes.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/fixtures/pages.yml
test/fixtures/versions.yml
test/lib/file_storage/local_file_test.rb
test/lib/file_storage/s3_test.rb

Pages can be filtered by:
- Site (`/pages?site={site name}`)
- Agency (`/pages?agency={agency name}`)
- URL (`/pages?url={url}` where `url` can contain `*` as a wildcard)
Versions can be filtered by:
- Hash (`/pages/{page id}/versions?hash={hash}`)
- Capture time (`/pages/{page id}/versions?capture_time={time}` where `time` is a [W3C-style ISO 8601 date/time](https://www.w3.org/TR/NOTE-datetime))
Note `time` can also be a range, as in `time..time`, e.g. `2017-04-01T10:00Z..2017-04-01T12:00Z` for versions between 10am and noon on April 1st.
Fixes #13.

Add some querystring filters for pages and versions!

---

app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb

It can be:
- valueless (`?include_versions`, but not `?include_versions=`)
- t
- 1
As a bonus, this is fairly generic so we can use it for other things in the future.

Allow a variety of booleans for include_versions

---

app/models/annotation.rb
app/models/change.rb
app/models/page.rb
db/migrate/20170517222310_change_annotation_author_to_not_null.rb
db/schema.rb
test/controllers/api/v0/annotations_controller_test.rb
test/models/annotation_test.rb
test/models/change_test.rb

When POSTing an annotation, any existing annotation by the current user on the current change gets edited/overwritten instead of appending a new annotation. The basic effect is that each change can only have one annotation per user, which is updated whenever the user posts a new annotation.
This shouldn’t really affect the API significantly; it allows a UI to push new annotations as the user works instead of waiting for them to explicitly commit (without winding up with a gazillion annotations).
Fixes #46

Make annotations editable

---

app/controllers/api/v0/pages_controller.rb
app/models/page.rb

While working on https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/48, I realized I was pushing the staging server pretty hard. I knew the queries being done at `/api/v0/pages` were sub-optimal, but hadn’t bothered to fix them. Now that the logger is sending me a big pile of e-mails, it seemed like a good idea to fix it :P
Anyway, the basic idea here is to turn `Page#latest` into an actual association (albeit a little bit of an oddball one) so that ActiveRecord can actually preload it. Now we perform 2 queries for the whole page instead of 101 queries.

Optimize the basic page listing call in the API

---

app/models/invitation.rb
test/fixtures/invitations.yml

Well this is embarrassing.
Ridiculously, the first invitation created would wind up having no invitation code. This is because I'm an idiot and am not used to Ruby's while/if-at-the-end-of-the-line style and didn't realize the code would first be initialized to Nil instead of a generated hash value. Once we had one bad invitation in the DB, others would behave because the routine would see that their Nil code collided with the original Nil code.
Also fixes the poorly-coded fixture that masked this issue in tests.
This is one of two problems we have with sending invitations and confirming new users in production. The other is #50.

Fix totally borked invitation code generation

---

.env.example
Gemfile
Gemfile.lock
config/environments/development.rb
config/environments/production.rb

**DO NOT MERGE:** Postmark still has to approve the account before we can send to most public e-mail addresses. This should happen by 2017-05-26.
Addresses #50.
Setup e-mail sending via Postmark. I’ve set up an account and this is working for me locally. When deployed, this will be sending from an account at my personal domain. We’ll want to change that (see discussion about domains and e-mail etc. in the EDGI Slack #tools_talk), but user accounts are kinda broken right now and I want to at least get them working so other people can test against the live DB without me manually setting up accounts in the console or cajoling GMail into behaving.

Send e-mails with Postmark

---

app/assets/stylesheets/application.css
app/controllers/api/v0/api_controller.rb
app/controllers/application_controller.rb
app/views/layouts/application.html.erb
test/controllers/api/v0/pages_controller_test.rb

fixes, [#67](https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/67), I haven't setup a test yet for the environment banner, if you need a test setup for it I'd recommend doing an integration test with capybara which I could setup.  I didn't want to add the dependency to your project without your input first since it would be bringing in a library just to test one thing.   I also added some color to the banner and made it center, hopefully it sticks out more.  
I added a test for the X-Environment header, its not very expansive, but I think with a little guidance I could add more tests.

Environment banner

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb
test/test_helper.rb

Ensure included versions on page API are ordered

---

app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/api_controller.rb
app/models/change.rb
app/models/version.rb
test/controllers/api/v0/versions_controller_test.rb

The first version of a page can’t be annotated (because annotations are really on the change between a version and its previous version — and there is no version before the first version). We raised an exception from down in the depths of the app for this before, which did not clearly indicate the problem. This provides clients with a 404 error (indicating the issue is on their side) and a clearer message about what was wrong (no previous version to annotate).
Fixes #81.

Return 404 error when annotating first version of a page

---

app/models/application_record.rb
test/models/application_record_test.rb

This is a fix for #85.
ActiveRecord does not actually try to figure out that a `joins(:some_association)` call may return multiple instances of a given record and coalesce them into a single result, so we also need to tell it to only get distinct results when auto-joining in `ApplicationRecord#where_in_unbounded_range`.
In #85, `where_in_unbounded_range` is used on pages’ association with versions to query on `capture_time`. This caused an INNER JOIN to versions, which meant we’d see duplicate page entries for every version that matched. We really only want *one* page entry if any of that pages’ versions that match.

Return unique records in `where_in_unbounded_range`

---

lib/differ/simple_diff.rb
test/lib/differ/simple_diff_test.rb

Send the version hash for each version being diffed to the differ. This allows differs to do smarter caching. Fixes #84.

Send hash of versions to simplediff differs

---

README.md

The installation instructions in the readme fail on clean Linux installs because of the lack of installed JavaScript runtime.

Fix #90 by adding NodeJs to installation instructions in README.md

---

README.md

This is kinda dumb, but the center alignment of the contributors table was really bugging me.

Align columns in contributors table

---

.env.example
config/initializers/differ.rb

I left DIFF_SOURCE in place in case we want to continue to run go-calc-diff alongside web-monitoring-processing similar utility for awhile.

Add differs from web-monitoring-processing#59

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb

This is a pretty similar issue to #85, discovered while adding remote login support for UI.
Joining pages to versions means our output will have repeated pages. The API, however, should always be returning a unique list of pages (with versions rolled up as attributes of the pages).
The `distinct` call here would be more technically correct if only used where we do a join, but always adding at the end like this *shouldn't* have major negative effects and protects against future mistakes if we add joins elsewhere.

Ensure no duplicate pages when querying by version attributes

---

app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/changes_controller.rb
app/controllers/api/v0/diff_controller.rb
app/controllers/api/v0/versions_controller.rb
app/lib/numeric_interval.rb
app/models/application_record.rb
app/models/change.rb
app/models/version.rb
config/routes.rb
swagger.yaml
test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/changes_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/fixtures/changes.yml
test/lib/numeric_interval_test.rb

Adds two routes (which one might have guessed at before but used to be 404s):
- `GET /api/v0/pages/{page_id}/changes` - list changes (ordered by `to_version`, then `from_version`)
This also supports the query args:
- `priority_gt` OR `priority_gte` - gets changes with a priority greater than (or equal to) the given value
- `priority_lt` OR `priority_lte` - gets changes with a priority less than (or equal to) the given value
- `GET /api/v0/pages/{page_id}/changes/{from_version_id}..{to_version_id}` - a single change
And removes all annotation-related stuff from the version routes:
- Remove `GET /api/v0/pages/{page_id}/versions/{version_id}/annotations`
- Remove `POST /api/v0/pages/{page_id}/versions/{version_id}/annotations`
- Remove `GET …

Add API endpoints for change models

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb

There was a leftover call to Version#current_annotation, which was removed. Also added a basic test for this endpoint, which I'm surprised I had failed to add before :(

HOTFIX: single-page GET was broken

---

app/models/change.rb
test/models/change_test.rb

ActiveRecord's `where` method can transparently take an ID or instance for collection attributes, but the `create` and `new` methods cannot. We used to rely on the former behavior, but that would break when new instances were needed. Now we explicitly ensure we have an ID and always use the ID attributes rather than the collection attributes.

HOTFIX: Always query changes based on ID attributes

---

lib/jwt_tools/jwt_auth_strategy.rb

I had been under the impression that `fail!` only failed the current strategy, but instead it halts all authorization, which broke basic auth! Instead call `pass`, which falls through to the next strategy, unless we got a token with user info. Then fail! if the user doesn't exist.

HOTFIX: Allow token auth to fallthrough to basic auth

---

app/controllers/concerns/paging_concern.rb
test/controllers/api/v0/pages_controller_test.rb

Fixes #111. I had thought Rails URL helpers would be smart enough to merge the `params` keyword argument with other keyword arguments that ultimately become params. They are not. Instead, explicitly merge `page` into the `params` argument so that it doesn’t get repeated.

Ensure paging links have `page` only one time in each link

---

app/controllers/api/v0/imports_controller.rb
app/jobs/import_versions_job.rb
app/models/import.rb
db/migrate/20170801192038_add_update_behavior_to_import.rb
db/schema.rb
swagger.yaml
test/controllers/api/v0/imports_controller_test.rb
test/fixtures/versions.yml
test/jobs/import_versions_job_test.rb
test/models/import_test.rb

Imports previously skipped versions that were already in the database (i.e. versions that have matching `capture_time` and `source_type` fields). In order to update bad imports, we need to be able to touch existing versions.
If you import as before, the behavior stays the same. However, if you provide the `update` query arg, you can customize how existing versions are handled:
- `?update=replace` Replaces all content in the existing version with new content
- `?update=merge` Merges the source_metadata fields (and replaces everything else)
Fixes #115

Add import flag to replace or merge existing versions

---

config/application.rb

Looks like I broke remote authentication in e70230a. An upgrade to rack-cors changed the behavior of `origins '*'` such that it now does not reflect the request's origin and instead actually sends '*' for the allowed origins header. That means authentication on our requests fails :(
See this change in rack-cors: cyu/rack-cors#142
We needed this behavior initially because it seemed like `Authorization` headers in our requests were getting stripped, but it seems like this may no longer be true (or, more likely, I mis-diagnosed the issue originally). That needs more testing, though. For now, force rack-cors to return to its earlier behavior.

HOTFIX: Reflect origin header for CORS auth

---

app/controllers/api/v0/versions_controller.rb
swagger.yaml
test/controllers/api/v0/versions_controller_test.rb
test/fixtures/versions.yml

This adds the ability to query Versions by fields in `source_metadata`, e.g:
- `/api/v0/versions?source_type=versionista&source_metadata[version_id]=12345678` to get the version with the Versionista ID `12345678`.
- `/api/v0/versions?source_type=versionista&source_metadata[errorCode]=404` to get all Versionista-tracked versions where the page went missing
- `/api/v0/versions?source_type=versionista&source_metadata[page_id]=987654&source_metadata[errorCode]=404` to get versions where a specific Versionista-tracked page went missing
This should help with processing scripts and tools @janakrajchadha is working on.
Fixes #123.

Query Versions by `source_metadata` fields

---

app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb

We previously did not include all the matching pages when paginating the results for a large query on a list of pages (two kinds of “pages” there, con't figure out a better way to phrase). This is because of some craziness with how ordering is handled when using limit/offset queries in ActiveRecord.
Specifically, ActiveRecord actually does _TWO_ queries when using `limit`/`offset` on queries that `include` associated records (e.g. version records that are associated with page records in this case):
1. A query for only the IDs of the primary record type (e.g. pages). This ensures the limit/offset isn't mispositioned by extra rows created when joining to the versions table.
In our case, that might look like:
```sql
SELECT DISTINCT
"pages"."uuid",
"pages"."updated_at" AS alias_0
FROM "pages" …
```

HOTFIX: query paging problems

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb

You must now use an `?include_latest` flag:
`GET /api/v0/pages?include_latest`
Note that if you use both `?include_latest&include_versions`, then `include_latest` is ignored.
Fixes #131.

Do not include latest version on pages by default

---

app/controllers/api/v0/versions_controller.rb
app/jobs/import_versions_job.rb
app/models/page.rb
app/models/version.rb
db/migrate/20170909151007_add_title_to_versions.rb
db/schema.rb
test/controllers/api/v0/imports_controller_test.rb
test/models/page_test.rb

Resolves #59 
This work adds a `title` attribute to the `versions` table, and supplies an `after_add` callback to `Page` model, which sets the `Page`'s `title` attribute to match that of the `Version` with the most recent `capture_time`.
I'm not quite familiar enough with the application at this point to know intuitively whether the `title` attribute on a `Version` should include a validation for presence as a mandatory field, but my best judgement led me to forego that addition, and simpy match it to the `Page`'s implementation of the same field.
Please let me know if I've missed anything or if there's anything else I can do to help on this ticket! 😄

Sync Page title with most recently captured version

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb

Sort versions in /pages?include_versions in descending capture_time order.

---

.env.example
app/controllers/api/v0/api_controller.rb
config/initializers/differ.rb
lib/api/api.rb
lib/differ/simple_diff.rb

The core of adding another diff is pretty simple, but I did a bunch of extra cleanup while I was here:
- Initializing `SimpleDiff` instances had a lot of rote, duplicated code. It now creates differs based on the env var name, so just need to provide with a list of differ env vars to use and nothing more. (I didn’t feel confident in just accepting any old `DIFFER_*` env var yet, so you still have to provide a list of allowed ones.)
- I also had to fix up some things on the processing side to support this (edgi-govdata-archiving/web-monitoring-processing#90), which made me realize we don’t really handle errors from the differ well. I changed things so that we respond with an actual error and use the same status code as the differ responded with.

Add visual HTML diffs

---

app/controllers/api/v0/diff_controller.rb

Pretty much what it says on the tin. Instead of filling in `diff_service_version`, we are removing it and differs themselves are responsible for including a `version` property in their response to the API, which will simply parrot it back out to the client in the `content` property.
Fixes #137.

Remove `diff_service_version` in diff response

---

.circleci/config.yml

Turns out `type: shell` is incorrect syntax and the CircleCI docs are a little spotty. More details: https://discuss.circleci.com/t/is-there-a-difference-between-run-vs-type-shell-steps/17022

Remove use of `type: shell` in Circle config

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/versions_controller.rb
config/initializers/oj.rb
test/controllers/api/v0/pages_controller_test.rb

Generally addresses #154.
This started out with some simple profiling and the addition of `Oj`, a faster JSON (de)serializer. That had a nice speed boost of just under 2x, so then I went a little nuts to bring memory way down (4-5x) reduction) and speed way up (about 5x). I don’t know that I’d recommend this approach for general use, but the page-related queries are *really* hot and desperately need all the optimization they can get, so I felt it made sense here.
In the following comparisons, “base” is the current, standard, Rails-y approach, while “Oj” is simply adding Oj (and restructuring slightly to get better use of it) in [the first commit](https://github.com/edgi-govdata-archiving/web-monitoring-db/commit/ed179545f7cf0e56ac50bad5b2d3d2377278ddb4), and “nutty optimizations” is [the …

Big perf/memory improvements in pages controller

---

app/assets/stylesheets/home.scss
app/controllers/api/v0/api_controller.rb
app/views/home/index.html.erb
lib/api/api.rb
test/controllers/api/v0/changes_controller_test.rb
test/controllers/api/v0/diff_controller_test.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb

Closes #122
As noted in #122, we should note in the API documentation
that authentication is required. @Mr0grog, di you have in mind
an overall statement about this at the top, a change to swagger.yml,
or both?

Require authentication for all API requests.

---

config/database.yml

This is meant for production/staging only, to help us migrate in a reversible way to RDS.
Basically, if a `DATABASE_RDS` environment variable is present, use it instead of `DATABASE_URL`. This is because Heroku (where things are currently deployed), automatically manages `DATABASE_URL`, so we want to avoid messing with it.
This is part of #143.

Prefer `DATABASE_RDS` env var to `DATABASE_URL`

---

app/controllers/concerns/paging_concern.rb

Use the `MAX_COLLECTION_PAGE_SIZE` environment variable to configure a different max size than the default (which is still 10,000).
Basically, 10,000 is too big for our current machines, but wasn’t sure hard-coding made sense if we can/will also put it on beefier hardware.

Make MAX_PAGE_SIZE configurable with ENV var

---

db/migrate/20171101214731_remove_page_uuid_site_index.rb
db/schema.rb

I have no idea what possessed me to make a multi-column index like this, since we never do a query on `UUID` + `site`. Instead, just index `site`. Tried this out on staging and it seems to have made a reliable performance improvement.
(Also totally forgot to push this! It’s been sitting around for a while.)

Remove uuid+site, add site-only index on pages

---

README.md
test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/changes_controller_test.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb

I didn’t pay close attention and didn’t realize how out of date #169 was, so merging broke tests. This fixes them.

HOTFIX: repair tests from bad merge

---

lib/tasks/copy_data.rake

Had this sitting around from earlier in the week and it seemed like it might be pretty useful for pulling in real data to test with.
This uses the API to pull in pages and their versions from other databases (e.g. production or staging). They keep they same ID the had in the remote environment, so this can be really helpful for bringing in real data to test.
Right now, it only does one page at a time.
Usage:
```sh
rake copy_page['https://api.monitoring.envirodatagov.org','YOUR USERNAME','YOUR PASSWORD','ID OF PAGE TO COPY']
```
Or for more verbose logging:
```
VERBOSE=true copy_page['https://api.monitoring.envirodatagov.org','YOUR USERNAME','YOUR PASSWORD','ID OF PAGE TO COPY']
```

Add rake task for copying data from remote DBs

---

.env.example
config/initializers/differ.rb
lib/differ/differ.rb
lib/differ/simple_diff.rb

The value of the `DIFFER_DEFAULT` environment variable will be used as the URL for a new SimpleDiff instance if no diff has been registered for a requested diff type. You can still keep explicitly registered differs via any environment variables named `DIFFER_*`; they’ll be matched before falling back to creating a default differ. This way, we can keep current configurations in place until the UI has updated to request the correct diff names (DB’s names don't quite match Processing’s names; see https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/133).
This also tightens up error handling of responses from the differ (since we’ll see them more often now). We should get on edgi-govdata-archiving/web-monitoring-processing#121 to make this better still.
Fixes #180 and …

Add a “default” differ type using `DIFFER_DEFAULT`

---

app/controllers/api/v0/diff_controller.rb
test/controllers/api/v0/diff_controller_test.rb
test/lib/differ/differ_test.rb

The idea here is that all the metadata and extra info the DB server provides should be in the standard `links` and `meta` sections of the response, while `data` should just be exactly what you'd get if you called the diff server directly. Makes a lot more sense in hindsight.
If we ever do decide to expose the differ publicly or if we write other tools that access the differ internally, this helps ensure the interface is standard and code can be shared. It also hopefully forces us to put things more in the right place.
Fixes #181.
**NOTE: Do not merge yet. This will be a breaking change for the UI, so it needs updates to be deployed first. There are a lot of things in flight there, so I think this will be easier if we hold off just a bit on merging.**

Make diff endpoint's `data` the raw diff data

---

app/controllers/concerns/paging_concern.rb
test/controllers/api/v0/pages_controller_test.rb

Don't just inherit the requested `chunk_size` for paging links; use the fixed validated version so that links are correct. Fixes #177.

Use the validated `chunk_size` in paging links

---

app/controllers/users/registrations_controller.rb
test/controllers/users/registrations_controller_test.rb

Kinda dumb. It assumed the request would include an invite code (which URLs in invite e-mails do, but it is obviously possible to arrive here without one). Fixes #198.

Don't crash loading registration page

---

Gemfile
Gemfile.lock
lib/file_storage/s3.rb

AWS has recently modularized the SDK gem so there is now one gem per service. Upgrading to V3 of the SDK is *huge*, so it's probably the right time to switch to a more trim and direct dependency on the S3 gem, which the only one we use. (Note that the major version for the full SDK gem is now 3.x, but the individual service gems are all new and at 1.x.)
This is an alternative to/replacement of #215.

Switch to using aws-sdk-s3 instead of full aws-sdk

---

config/environments/production.rb
swagger.yaml

Our canonical names are all `*.monitoring.envirodatagov.org`. We need to actually be able to turn the Heroku stuff off, and to do that, all our examples and default values should point to the domain name we actually own and manage.

Remove references to *.herokuapp.com domain

---

.rubocop.yml
.rubocop_todo.yml
app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/maintainers_controller.rb
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/tags_controller.rb
app/jobs/import_versions_job.rb
app/models/concerns/taggable.rb
app/models/maintainer.rb
app/models/maintainership.rb
app/models/page.rb
app/models/tag.rb
app/models/tagging.rb
config/routes.rb
db/migrate/20180128062846_create_maintainers.rb
db/migrate/20180207031149_create_tags.rb
db/migrate/20180207061655_copy_agency_and_site_fields_to_associated_models.rb
db/migrate/20180212043742_dedupe_pages_with_multiple_agencies_or_sites.rb
db/schema.rb
lib/api/api.rb
swagger.yaml
test/controllers/api/v0/imports_controller_test.rb
test/controllers/api/v0/maintainers_controller_test.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/tags_controller_test.rb
test/fixtures/maintainers.yml
test/fixtures/tags.yml
test/models/page_test.rb

~**Work in progress; do not merge!**~
Fixes #24.
Replace the `agency` field on `Page` models with an N:M relationship to a new `Maintainer` model; replace the `site` field on `Page` models with an N:M relationship to a new `Tag` model.
Note: this PR intentionally leaves the old `site` and `agency` fields in place so as not to break existing clients. We’ll remove them later when we’re confident most clients are working in terms of maintainers/tags.
OK! This is most of the way done now, so I think it’s ready for feedback on whether this looks right. Some questions/things I’d really like feedback on here:
1. Do we need all the extra routes for listing/renaming/adding maintainers and tags as above?
2. Tag names are *not* case-sensitive (for querying, that is; the response shows the case they …

Replace agency → maintainers & site → tags

---

db/migrate/20180128062846_create_maintainers.rb

One extension we are using was missing from the live DB. I think this is left over from #153.
Still running the migrations on staging, but everything else seems good so far (lots of data for the migrations doing data transformation).

HOTFIX: Fix up DB extensions

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb

Querying by capture_time in combination with other version parameters (`hash`, `source_type`) was broken in the maintainers update. In addition, I'm not sure why I flipped it to a left_outer_joins in the first place, which is clearly the wrong join for this particular query. I think this must have been a mistaken thing that got committed when I was trying to get all the various query params to work happily together.

HOTFIX: querying by capture_time + source_type/hash

---

app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/changes_controller.rb
app/controllers/api/v0/maintainers_controller.rb
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/tags_controller.rb
app/controllers/api/v0/versions_controller.rb
app/controllers/concerns/sorting_concern.rb
swagger.yaml
test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/changes_controller_test.rb
test/controllers/api/v0/maintainers_controller_test.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/tags_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/fixtures/changes.yml
test/fixtures/pages.yml
test/fixtures/versions.yml
test/test_helper.rb

Fixes #165.
The overall approach here is inspired by @tylerferraro’s original PR from a few months ago. This adds sorting to all list requests with a `?sort=field:order,field:order,...` query parameter. For example:
```
GET /api/v0/pages?sort=title:asc,updated_at:desc
```
Sorting happens in order, so results are sorted by the first field, then, only if that field is equal, by the second field, and so on.
Open questions:
1. Is `sort` the right name here? (vs. `order`? or something else?)
2. Is comma-separated the right thing, or should this be `?sort[]=title:asc&sort[]=updated_at:desc`?
3. Is `field:order` the right way to go here? Seems like that sounded best to everyone earlier on.

Add sorting via `?sort=` query parameter

---

app/jobs/import_versions_job.rb
test/controllers/api/v0/imports_controller_test.rb
test/jobs/import_versions_job_test.rb

This makes things much easier for client libraries (i.e. it’s needed for edgi-govdata-archiving/web-monitoring-processing#167). While we're add it, just do better type checking and error messaging around the page fields in general.

Allow `null` value when importing maintainers/tags

---

.rubocop.yml
.rubocop_todo.yml
Gemfile
Gemfile.lock
Procfile
app/jobs/import_versions_job.rb
app/lib/surt.rb
app/lib/surt/canonicalize.rb
app/lib/surt/format.rb
app/models/page.rb
db/migrate/20180227021126_add_capture_url_to_version.rb
db/migrate/20180227024610_add_url_key_to_page.rb
db/migrate/20180227034314_dedupe_pages_with_matching_url_keys.rb
db/schema.rb
swagger.yaml
test/controllers/api/v0/imports_controller_test.rb
test/lib/surt/surt_test.rb
test/models/page_test.rb

~**Work in progress; do not merge!**~
Add support for canonicalizing URLs with SURT (Internet Archive’s “Sort-friendly URI Reordering Transform”) so that we can support pages whose content may come from more than one exact URL (as is often the case when we try to import data from Internet Archive).
The idea here is that we add a `url_key` field to Pages and, when importing, match pages by that field *when they don’t match by an exact `url`* (this lets us easily disambiguate two pages with the same `url_key` that should actually be separate by simply making a new Page record with an exact URL match).
Fixes #185.

Canonical, SURTified Page URLs

---

Procfile

Lesson learned: this is great for schema migrations, but for large data migrations, it can be a big problem. This was not the brilliant idea I thought it was.

Remove auto-migrations as part of Heroku release process

---

app/jobs/import_versions_job.rb
test/controllers/api/v0/imports_controller_test.rb

While working on cleaning up the aftermath of edgi-govdata-archiving/web-monitoring-versionista-scraper#71, I realized we weren't surfacing validation errors that were built into our Page models. This adds that, but in the process, I realized we were also handling ActiveRecord::RecordInvalid errors incorrectly. So this fixes that, too.

Fix ActiveRecord error messages in import job

---

Gemfile.lock

This resolves the CVE vuln from a few days ago.
Changelog: https://github.com/flavorjones/loofah/blob/master/CHANGELOG.md#221--2018-03-19

Upgrade loofah gem

---

lib/archiver/archiver.rb

Internet Archive stores all the redirects in the original request, which means they get replayed to us or anyone else who tries to retrieve an IA page. It turns out that sometimes that's a lot of redirects! Increase our limit to 10 for now (the default in HTTParty is 5).
This fixes some issues I hit while working on https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/174.

Increase redirect limit to 10 when archiving a URL

---

test/controllers/api/v0/pages_controller_test.rb
test/fixtures/pages.yml
test/fixtures/versions.yml
test/models/page_test.rb

AKA fix test failures on some Linuxes.
It turns out Ubuntu desktop vs. Ubuntu server vs. Mac vs. Windows have different system-level libraries for text collation (sorting). What I did not expect was that *Ruby* does not use them, while *Postgres* does. And, most painfully, `.` vs. `5` sorts differently across some of these systems.
What this all adds up to is odd-seeming test failures around sorting on Ubuntu Desktop because we sort pages with the URL `example.com` and `example2.com` and then validate the sort result in Ruby (which doesn't work because Ruby sorts differently from Postgres there). I'm not sure what the “right” answer is here, so I've just modified the fixtures in such a way that we simply don't hit this scenario.
@gblike does this fix it for you? If so I’ll merge.

Change fixtures to sort the same across systems

---

app/controllers/api/v0/versions_controller.rb
app/jobs/import_versions_job.rb
lib/api/api.rb
lib/archiver/archiver.rb
test/controllers/api/v0/imports_controller_test.rb
test/lib/archiver/archiver_test.rb

If imports include a hash, use it to validate raw content when downloading and archiving it. Fixes #262.

Add hash validation to Archiver + validate imports

---

lib/archiver/archiver.rb
test/lib/archiver/archiver_test.rb

When downloading raw content, the archiver should retry (up to two additional times) for gateway errors and timeouts. If the final result was still a gateway error, we process it as a success anyhow -- its possible that the actual snapshotted response was a gateway error and we don't want to fail to save that.
Fixes #261.
*Note: this depends on #271*

 Add retry/backoff to Archiver when downloading raw content

---

app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/imports_controller.rb
app/jobs/import_versions_job.rb
app/models/import.rb
db/migrate/20180413051144_add_create_pages_to_imports.rb
db/migrate/20180415063842_add_processing_warnings_to_imports.rb
db/schema.rb
test/controllers/api/v0/imports_controller_test.rb

To prevent imports from creating completely new pages (when there's a previously unknown URL in the import data), set the `create_pages` query argument to false in `POST /api/v0/imports?create_pages=false`.
Fixes #265.

Add `?create_pages=false` import query argument

---

app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/versions_controller.rb
app/jobs/import_versions_job.rb
app/models/page.rb
app/models/version.rb
db/migrate/20180415065623_add_different_to_versions.rb
db/schema.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/models/version_test.rb

This is an implementation of the alternative approach to handling imports of records that don’t differ from a previous capture of the same page (#266). It adds a `different` flag to the Version model and a routine for updating it.
Still needs:
(Based on #277)

Add flag for qualifying versions as different from previous (#266 alternative)

---

.env.example
app/controllers/api/v0/pages_controller.rb
swagger.yaml
test/controllers/api/v0/pages_controller_test.rb

Fixes #264 
This is my first attempt at writing code for -db, so I'm probably not doing this idiomatically. I went the very conservative route of mostly commenting out code and skipping tests because we'll re-implement this functionality as described in #274. We'll need edgi-govdata-archiving/web-monitoring-ui#218 merged and deployed before deploying this.
Good news, I learned about implicit behavior in Rails and got to dig around in this repo!

Disable returning versions from /pages and /pages/{page_id}

---

.circleci/config.yml
docs/generating-new-seed-data.md

I've been meaning to generate better seed data for a while (where most pages have multiple versions and where there are a fair number of pages), and finally did so for DCFemTech's hackathon this past weekend. I figured I'd add the script I wrote for it here so it's easy to run again if we need to (maybe to generate a different size import or just to create newer data).

Add instructions for generating new seed data

---

.gitignore
README.md
config/database.yml

OK, we've had a lot of back-and-forth and confusion over getting databases configured right when they require passwords or are running on different ports, etc. (#294, #358, #359)
The idea here is similar to #294; you can specify a special config by using the `DATABASE_URL` environment variable, which requires you to set all aspects of the connection. Additionally, this provides a workaround for the fact that Rails runs database rake commands twice with different configs if you are in the development environment.
- If you are in a production or test environment, just set the `DATABASE_URL` environment variable.
- If you are in a local environment, where you are using both `development` and `test` configurations, you can either:
- If you have the old-style setup with a Postgres DB requiring …

Yet another take on DB configuration

---

CONTRIBUTING.md
README.md

Fixes part of [umbrella issue #111](https://github.com/edgi-govdata-archiving/web-monitoring/issues/111) to add CoC to all of the wm repos.

Add Code of Conduct to README and CONTRIBUTING docs

---

app/controllers/api/v0/annotations_controller.rb
app/models/annotation.rb
lib/api/api.rb
test/controllers/api/v0/annotations_controller_test.rb

Fixes #113. We previously had oddball server errors for sending empty bodies or empty objects as annotations. This makes both of those cases `4xx` errors.
- Empty POST body: 400 (bad request)
- Empty annotation object: 422 (unprocessable entity)
The issue was originally noted in edgi-govdata-archiving/web-monitoring-ui#82. Based on that, I’m wondering if I should actually be accepting empty objects (but not empty bodies). The current code here just formalizes existing behaviors, where we rejected empty objects in one part of the code and then failed to handle it later. Now that POSTing a new annotation *replaces* your previous annotation (see #48), maybe we should allow empty objects.

Stop exploding when posting empty annotations

---

.circleci/config.yml
.env.example

We're migrating S3 data between AWS accounts, which also means making new buckets. Instead of `edgi-versionista-archive`, we now have `edgi-wm-versionista`. We're still allowing the old buckets, though, because we haven't actually moved all the data yet.
This is a subtask of edgi-govdata-archiving/web-monitoring#101.

Add new S3 buckets to ALLOWED_ARCHIVE_HOSTS

---

lib/tasks/data/20180926_move_versionista_s3_data.rake

This adds the migration code as a rake task. We've talked before about issues with extremely large data migrations, so this is my first take at moving them out of the normal migrations path by making each one a rake task. I'm thinking we'll namespace them all under `:data`.
This is part of edgi-govdata-archiving/web-monitoring#101.

Add data migration for new S3 buckets

---

config/initializers/file_storage.rb

We correctly set the region for public archival storage, but not for internal, private storage of working files. The old storage bucket was in `us-east-1` (the default), so this was easy to miss until edgi-govdata-archiving/web-monitoring#101 was solved.

Ensure AWS region is set for internal/private storage

---

lib/archiver/archiver.rb
lib/file_storage/s3.rb
test/lib/archiver/archiver_test.rb
test/lib/file_storage/s3_test.rb

Since we store files by their hash, we know that a hash that is already in the store should be good, so we can stop early; there's [generally] no reason to download the content at all. If you *really* want to verify that the content at the URL to archive matches the already known hash, you can set the `force: true` argument.
This also updates the S3 storage layer to actually check whether the object is in the bucket (as opposed to just whether the bucket is correct). I think I had intended to do this before, but never got around to it! :(
Finally, the order of checks in `Archiver.already_archived?()` is reversed so that the cheapest check is first (there's no network hit for determining whether the URL is at an allowable, external archive host).
Fixes #377.

Stop archiving if the hash is known and archived

---

.circleci/config.yml

We previously used CircleCI’s “approval” feature for managing the publishing of docker images from the `master` branch. Unfortunately, experience has shown us that what sounds like a promising feature is actually poorly executed enough that it causes confusion and wasted build time on CircleCI. Because nobody gets notified that a job is awaiting approval and jobs can't expire (see *many* CircleCI support tickets requesting this from plenty of users), workflow approvals often get forgotten and are then stuck hanging until someone comes along to clean them out.
Instead, we're adding a `release` branch. Any pushes to this branch will get automatically published to Docker Hub, no approval needed. Management is now handled by someone manually adding a commit from `master` onto `release`.
I’m …

Automatically publish docker images from release branch

---

app/controllers/api/v0/versions_controller.rb
app/jobs/analyze_change_job.rb
app/models/change.rb
app/models/version.rb
lib/tasks/import_from_sheets.rake
swagger.yaml
test/models/change_test.rb
test/models/version_test.rb

This adds to additional query params to endpoints that return a version or a list of versions:
- `?include_change_from_previous`
- `?include_change_from_earliest`
That include a field with the given name whose value the the change object (if any) representing the the change relative to the requested version. This is implemented *really* inefficiently (so it's very good that you have to ask for it), but I couldn't think of any way to do this better without adding a lot of denormalization. Regardless, I think it's still faster to have the API include this feature than to have the scraper make more API calls when building analyst task sheets.
(One alternative I’m imagining is querying for all Change objects related to captures in a given timeframe via a non-existent `/changes` endpoint and …

 Add `?include_change_from_*` to version endpoints

---

.env.example
Dockerfile
Procfile
app/jobs/analyze_change_job.rb
app/jobs/import_versions_job.rb
lib/differ/differ.rb
lib/tasks/analyze_changes.rake
test/controllers/api/v0/imports_controller_test.rb

This changes several things around our auto-analysis code to firm it up a bit:
1. Cleans up the overall hotfix-related logic so it’s less janky (#411)
2. Loosens the restrictions put in place by the hotfix. Now that we’ve merged edgi-govdata-archiving/web-monitoring-processing#289, we don’t need the strict safety and we can attempt more diffs. **However, this also adds an `ANALYSIS_REQUIRE_MEDIA_TYPE` env var you can set to get the strict, hotfix-style behavior back an emergency.**
3. Splits jobs into two separate queues so they are easy to move to separate processes/images/pods/whatever later. There is now an `import` queue and an `analysis` queue. By default, the Import Worker image runs both, but you can change that with the `QUEUES` environment variable.
4. Adds a rake task for …

Clean up and loosen auto-analysis hotfixes

---

config/environments/production.rb

This should allow Kubernetes liveness/readiness probes to make HTTP requests.
per documentation: https://edgeapi.rubyonrails.org/classes/ActionDispatch/SSL.html
via this SO post: https://stackoverflow.com/a/38572725/1221924

Exempt the healthcheck endpoint from force_ssl.

---

config/initializers/new_framework_defaults.rb

In #418, @jsnshrmn noted that @danielballan’s change to enable non-SSL responses for the healthcheck endpoint didn’t work. That was because the `ssl_config` option was be overridden and re-set by this initializer (initializers run after the environment-specific config files). This is the fix.
The option this was setting is the default — so it wasn't doing anything meaningful other than blowing away the config option that we were setting in the `production` environment config file.
This initializer just sets properties to their new defaults in Rails 5 (it's still hanging around from a very old upgrade) so you can test options that are about to change (or that just changed, depending on which side of the upgrade you're using it on). I'm pretty sure we could just delete this whole …

Remove conflicting SSL config from Rails upgrade initializer

---

lib/archiver/archiver.rb
lib/differ/simple_diff.rb
test/lib/differ/simple_diff_test.rb

Hopefully this is pretty straightforward. We should generally be expecting that any upstream HTTP service could have intermittent failures (general network problems, machine being restarted, etc). We weren’t doing that with `SimpleDiff`, but this adds it.
Fixes #414.

Add retry/backoff logic to SimpleDiff

---

README.md

We had issues with sending e-mails because I forgot to ensure our new configuration (with explicitly listed queues) included the `mailer` queue (see [the fix in ops](https://github.com/edgi-govdata-archiving/web-monitoring-ops/commit/bb23993ac61313805ce31b9b3ebe99154423b1a3)). This documents the available queues so it's easier to know what options are available and to know whether you are processing all of them.

Document job queues in README

---

swagger.yaml

This adds a description, the `create_pages` query param (it was missing), and a schema for the types of objects you should be POSTing. This is one the many endpoints we’ve not done a great job spending the time documenting, but we really need to do so to support qri-io/walk#16.

Add much more detail to `POST /imports` docs

---

app/models/concerns/simple_title.rb
app/models/page.rb
app/models/version.rb
lib/tasks/data/20181124_normalize_titles.rake
test/models/page_test.rb
test/models/version_test.rb

Fixes #430 by adding a concern (a mixing for models) that normalizes the `title` attribute before saving. Both the `Page` and `Version` models use it. I’m thinking it might make sense to extend to tags and maintainers in the future, but that’s out of scope here.
Also adds a data migration to fix existing records with bad titles.

Ensure Version/Page titles are normalized to be a single line, remove surrounding spaces, etc.

---

app/controllers/api/v0/pages_controller.rb
app/models/page.rb
swagger.yaml
test/controllers/api/v0/pages_controller_test.rb

We already had an `?include_latest` and this adds an `?include_earliest` to match. This comes without an issue discussing it because repeated recent failures in our analyst sheet generation have made the need for this abundantly clear (otherwise we wind up making *thousands* of queries to `/api/v0/pages/{id}/versions?chunk_size=1&sort=capture_time:asc` to get the earliest version of each page on each sheet generation run).

Add `?include_earliest` query param for pages

---

config/initializers/httparty.rb

In some situations, Wayback screws up the `Content-Encoding` header when sending gzipped data (see the comments in the patch here or the original issue for more details). They don't have any clear timeline on fixing the issue, so this hack may stay in indefinitely. If we ever switch HTTP libraries, we'll unfortunately have to figure out how to fix it or stop using gzip.
The alternative is to send `Accept-Encoding: identity` to disable gzipping for this content entirely. I’d like to avoid that since we are often pulling in a lot of data, but it is the safer fix. Happy to entertain objections on that front :)
Fixes #433.

Patch HTTParty to handle bad Wayback gzip headers

---

lib/tasks/data/20181124_normalize_titles.rake

I failed to properly escape the new `title` field value in the data migration for #436, resulting in https://sentry.io/environmental-data-governance-/db-prod/issues/787187315/activity/
This is pretty simple — just make sure we `Version.connection.quote` the new title.

Quote title text in data migration

---

app/controllers/api/v0/changes_controller.rb
app/models/page.rb
test/controllers/api/v0/changes_controller_test.rb
test/fixtures/changes.yml
test/fixtures/versions.yml
test/models/change_test.rb

It turns out we were spuriously listing ALL changes (not just the changes for a specified page) at `/api/v0/pages/{page_id}/changes`, which is totally and completely wrong. We also had a wrong test verifying wrong behavior. Don't know how this ever made it in, but it's fixed now.

Ensure `/pages/{id}/changes` lists correct changes

---

app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/versions_controller.rb
app/models/page.rb
app/models/version.rb
db/migrate/20181204192154_add_status_to_versions_and_pages.rb
db/schema.rb
lib/tasks/data/20181204_set_version_status.rake
swagger.yaml
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/fixtures/pages.yml
test/fixtures/versions.yml
test/models/page_test.rb
test/models/version_test.rb

This fixes #450, and does some of #451:
- Adds `status` as a nullable integer field to page and version records.
- Sets up validation so we get nice importing behavior.
- Adds a data migration for filling in `status` on *versions* (but not pages). Note we shouldn’t *run* this migration until all our ETL tooling starts sending `status` as a top-level field instead of in `source_metadata`; that way we only have to run it once.
- Adds querying via `?status={value}`, where `{value}` is an interval. We added interval support in #104 for `priority` and `significance` on annotations. It lets you do some nice stuff using standard mathematical notation:
- `?status=404` filter by an exact status
- `?status=[400,500)` get all 4xx statuses by using an interval with an inclusive start and an exclusive …

Add `status` fields to versions and pages

---

app/models/version.rb
lib/tasks/data/20181204_set_version_status.rake
lib/tasks/data/20181205_update_version_different.rake
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/models/version_test.rb

I originally thought it might be important to differentiate between the same content from multiple sources. That was probably wrong in retrospect, and especially so not that we are more actively using data from multiple sources and not attempting to differentiate much between them in pretty much any context.
Fixes #454.

Change `Version#different` to ignore source_type

---

app/jobs/import_versions_job.rb

We were previously tracking versions as added (and thus triggering auto-analysis) if we touched the version in any way. In reality, we should probably only automatically trigger a new analysis if it was actually a new version we *created.*
This is a proposed fix for #458. Should we add some other criteria here? Are there kinds of *updates* that should also trigger analysis? If so, what?

Only track a version as added if it was new

---

config/environments/production.rb

After updating, Bundler helpfully gave me the following message:
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.
Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.
We don't currently use i18n, but we should make sure it's correctly set up in case we do in the future.

Follow new recommendation for i18n config

---

app/models/page.rb
lib/tasks/data/20190112_add_page_domain_tags.rake
test/models/page_test.rb

When pages are first created, they now automatically tag themselves with two tags:
- `domain:{domain name}` (e.g. `domain:www.nmfs.noaa.gov`)
- `2l-domain:{second-level domain name}` (e.g. `2l-domain:noaa.gov`)
Fixes #470.
---
NOTE: I *could* do a bit more work here and use `around_save` to ensure the tags always match `url` field, even if the `url` changes, but:
- We *shouldn’t* be changing that field
- In a far future where pages have multiple URLs through time, we’d still be *adding* to a list and therefore probably *adding* domain tags
Based on that, complicated code to remove old tags if necessary and add new ones seemed like non-useful complexity at this point. Please say the word if you think I should add support re-writing the domain tags if `url` changes.

Tag pages with domain, second-level domain

---

app/jobs/import_versions_job.rb

If a version had the same content as the version that preceded it, then there's not a whole lot of point in auto-analyzing it -- there's nothing useful in the change between it and preceeding version or between it and the first version (because that change will be the same as between the preceeding version and the first version). Don't queue these versions for auto-analysis.
Noticed this while dealing with the massive number of analyses we queued up when I backfilled a month’s worth of Wayback versions yesterday. It wouldn’t have made a *huge* difference (maybe 10%; I didn’t do a deep analysis), but still seems like a worthwhile optimization.

Only auto-analyze versions that were different

---

app/views/invitation_mailer/invitation_email.html.erb
app/views/invitation_mailer/invitation_email.text.erb
test/mailers/invitation_mailer_test.rb

Improve Invitation email text

---

Gemfile.lock

Ever since I finally upgraded to MacOS 10.14 last month, I've been having issues with the Rails console. Turns out it's a problem with Bootsnap that seems to have gotten fixed in the latest version.
I’m going to go ahead and merge this straightaway, since it’s a minor dependency update that fixes immediate issues.

Upgrade Bootsnap to 1.4.0

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

A while back I did this funky thing where the environment variable that controls the default *host* in all the URL helpers is called `HOST_URL`, which implies it’s a URL, and then stuck things like `https://api.monitoring.envirodatagov.org/` in it, which, well, is a URL, but definitely not a host, and further confused things.
It turns out Rails will happily use the scheme provided in there anyway (!), so that was really convenient. But what it failed to do was handle the trailing slash—an absolute path also starts with one, so you wind up getting URLs like `https://api.monitoring.envirodatagov.org//whatever` (not the double slash at the start of the path). While we should have more correct configuration, we could also gracefully handle incorrect configuration by removing trailing slashes, …

Ensure default URL host never has a trailing `/`

---

README.md

It's unclear whether this has *always* been true, but at least the
version of Rails we use now needs postgres to have superuser
privileges to run the tests. @Mr0Grog and I tried several other
invocations, and as the documentation says the fixtures really do
need full superuser permissions.

Rails test fixtures require postgres superuser.

---

README.md
app/jobs/import_versions_job.rb
db/seeds.rb

This PR finishes the work of @patcon in https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/293 by printing out the progress of the import when seeding the database.
In addition to rebasing the commits, this integrates @Mr0grog's feedback and only prints lines in Development to prevent cluttering up the production logs.

Add logging to seed data import (in Development only)

---

.circleci/config.yml
Gemfile
Gemfile.lock
bin/worker_dev
config/environments/development.rb
test/application_system_test_case.rb
test/fixtures/invitations.yml
test/system/user_test.rb
test/system/users_test.rb

- Sets up Rails system tests, including capybara and capybara-email
- Creates a first system test that tests inviting a new user, confirmation, promotion to admin, demotion, and deletion
- ~~Within the development environment, replaces Sendmail delivery with letter_opener gem~~ unrelated to the system testing and removed
- Creates a binstub to start the job worker process during development
Note: I am using `rack_test` instead of Selenium Chromedriver because that has more complicated setup than I wanted to tackle right now.
This is a first step towards #34 by wrapping the existing auth system with tests.

Add system tests for user lifecycle

---

app/assets/data/swagger.yaml
app/assets/data/swagger.yml
swagger.yml

- Removes hardcoded host and protocol which are [optional in the swagger spec](https://swagger.io/docs/specification/2-0/api-host-and-base-path/#host) to fix #292 
- Places the actual `swagger.yml` file in `app/assets` and places a symlink in the project root to fix #455

Use relative host for swagger; place actual file in app/assets

---

db/migrate/20190531175430_remove_admin_from_users.rb
db/schema.rb

Fixes #34 (Most of the work was by @bensheldon in #533, this just cleans up the last bit!)

Add migration to drop the `admin` column for users

---

.circleci/config.yml
Gemfile.lock

Manage gems with v2 of Bundler. This is a bit of a major upgrade, and since bundler is what manages our dependencies, people will have to update their local Bundler install manually. That should be as simple as `gem install bundler` on the command line.
NOTE: this depends on #490.

Upgrade bundler to v2

---

app/views/users/registrations/new.html.erb

This PR fixes a deprecation warning from Devise:
```bash
DEPRECATION WARNING: [Devise] `DeviseHelper.devise_error_messages!`
is deprecated and it will be removed in the next major version.
To customize the errors styles please run `rails g devise:views` and modify the
`devise/shared/error_messages` partial.
(called from block in _app_views_users_registrations_new_html_erb___2844399626396461444_70316102091520 at /Users/bensheldon/Repositories/edgi-govdata-archiving/web-monitoring-db/app/views/users/registrations/new.html.erb:4)
```
It looks like this change has previously been made in another template:
https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/3cba9a45e10430270f245d658e3c736974eb8708/app/views/users/registrations/edit.html.erb#L3-L5

Fix deprecation warning for `DeviseHelper.devise_error_messages!`

---

app/models/user.rb
test/models/user_test.rb

When users are first created, make sure they are granted `view` and `annotate` permissions.
Fixes #549.

Give new users view and annotate permissions

---

app/models/version.rb

When looking for the `next` or `previous` version, we should almost always be looking for the next/previous version that was *different*. This was causing a lot of issues with calculating links for analysts, because new, non-different versions would be inserted after an analysis was done, and the analysis would be lost (because we'd try and retrieve it for the current vs. "previous" version, but "previous" was no longer the right thing).
This makes the default behavior one in which we check the different flag, but optionally lets you say `next(different: false)` to get the next version regardless of whether it's different.
This will also have the happy byproduct of making sure we are always analyzing versions that are different—it looks like we may have frequently been doing relatively …

Check `different` flag in `version.next/previous` and associated methods

---

db/migrate/20190617231901_add_common_indexes_to_versions.rb
db/schema.rb

We frequently filter Versions by several fields that don't have indexes, and that causes some real slowdowns. This adds indexes for them.
In local development, this hasn’t been a problem, but our Versions table in production has gotten big enough that we are seeing some real slowdowns. There’s also probably other optimizations we could make here, but I am no Postgres expert and this is a good start for now.

Add indexes for commonly searched fields on Version

---

test/mailers/invitation_mailer_test.rb

These two names are synonyms, but `update_attributes` is deprecated in Rails 6.

Replace `update_attributes` with `update`

---

app/controllers/api/v0/pages_controller.rb

This is a first step to #348, removing `lightweight_query`. It adds an environment variable, `USE_LIGHTWEIGHT_QUERY`. If the variable is set, the old functionality will be used, but if not, it will default to normal ActiveRecord functionality. This way, we can have an emergency switch to flip it back on if things go wrong. In a later PR, we can remove the functionality (and this env var) entirely.
Note this has a kind of complicated way of accomplishing the `?include_versions` query. I couldn't figure out how to make it work in ActiveRecord as nicely as it does in `lightweight_query`, but I'm also not *super* worried about it since that whole thing is turned off and will probably be removed anyway. @bensheldon if you can make this work better than me, go for it.

Switch off `lightweight_query` by default

---

.env.example
README.md

Add more explanation to `.env.example` and to the README about how data is managed and stored in the application. Also explain the overall data model and document the public access user on staging (see edgi-govdata-archiving/web-monitoring-ui#220).
Hopefully this is clarifying and not confusing! See here for a full render of the new README instead of a diff, if that helps: https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/249-469-explain-just-who-gets-trusted-to-hold-your-gooses-golden-eggs-and-where/README.md
Fixes #249.
Fixes #469.

Document `ALLOWED_ARCHIVE_HOSTS` and S3 Buckets

---

app/assets/data/swagger.yaml
app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/changes_controller.rb
app/controllers/api/v0/maintainers_controller.rb
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/tags_controller.rb
app/controllers/api/v0/versions_controller.rb
app/controllers/concerns/paging_concern.rb
test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/changes_controller_test.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb

For large tables, counting the number of possible results (in order to determine the URL for the *last* chunk in a result set) turns out to be extremly expensive. (For example, in our production `versions` table, the main query takes < 20 milliseconds, but counting the totals takes 18,000 milliseconds.) Instead, only count the total results and only include the URL for the last chunk if a user explicitly requests it.
In the future, we might move to an entirely different paging structure (that's not offset-based). See #579 for more.
NOTE: we need to update and redeploy scripts that use the `meta.total_results` before merging and deploying this:

Only include totals in list endpoints if `?include_total=true`

---

app/controllers/api/v0/pages_controller.rb

This is a follow-on to #582, where we *disabled* `lightweight_query`. This commit fully removes it and finishes off #348.

Fully remove `lightweight_query`

---

lib/tasks/copy_data.rake

The important change here is that we now make sure to iterate through *all* the versions of a page and copy them in the `copy_page` rake task, instead of only copying the first 100 pages (i.e. the first “chunk”).
While I was at it, I added a few helpful features:
- Stop early if there was a validation failure adding the page.
- Log all failed versions and the validation errors that failed them (but don’t stop in the middle for these).
- Log how many versions were skipped because you already had them.
- Allow specifying login credentials for the remote API as environment variables instead of command-line arguments. The names are the same as the ones you’d use with the [Python API wrapper in the -processing project](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/c46 …

Ensure we get ALL versions in `copy_page` rake task

---

Dockerfile
README.md

closes #583 
Since `MAINTAINER` instruction is deprecated, the directive has been switched to `LABEL` which is a more flexible version and is recommended as per docs.

Switched maintainer to label directive

---

app/controllers/api/v0/api_controller.rb

In dev mode, we used to show most errors with Rails’s standard error page, which gives you some nice debugging tools. However, that’s really not useful if you are testing a client against a local server. This change makes sure we format errors as JSON even in dev mode if the requester asks for JSON (either via the `Accept: application/json` header or the `.json` extension on a request).
This also adds stack traces to the error data in dev mode.
Fixes #614.

Format errors as JSON in dev mode

---

app/controllers/api/v0/pages_controller.rb
test/controllers/api/v0/pages_controller_test.rb
test/fixtures/versions.yml

When querying pages by `capture_time`, we whould be disregarding versions a page might have that are non-different (they don't actually represent a different version from the previous because they have the same hash). You can opt back into the old behavior (including pages with non-different captures) by passing `?different=false` when querying. This matches how queries on the versions collection work.
Fixes #565.

Filter non-different captures in page queries

---

app/jobs/import_versions_job.rb
test/jobs/import_versions_job_test.rb
test/test_helper.rb

The Internet Archive importer has been sending `hash` instead of `version_hash`, which means its hashes haven't been respected! Instead, we've been ignoring them and setting the hash to whatever we got when archiving the content at `uri`. :(

HOTFIX: respect hashes in import records

---

.circleci/config.yml

We actually already have all the v2.1 features turned on; this just updates our config file to declare v2.1.

Update CircleCI to v2.1

---

.circleci/config.yml
.rubocop_todo.yml

Update config files for CircleCI and Rubocop:
- The Rubocop `Metrics/LineLength` cop was renamed to `Layout/LineLength`.
- The `--path` option for `bundle install` was deprecated. Use an environment variable instead.
- Add a fallback cache key for dependencies to speed things up.

Update CircleCI and Rubocop config files

---

.circleci/config.yml
app/jobs/analyze_change_job.rb
app/jobs/import_versions_job.rb
test/jobs/import_versions_job_test.rb

Closes #564.
Creates a CircleCI job, running in parallel to the `build` job that invokes the seeds script. Uses a few new CircleCI features of "executors" (reusable docker configuration block) and "commands" (reusable step blocks).

Add CircleCI job to run seeds script

---

app/jobs/analyze_change_job.rb

Concurrent-ruby has a `zip` method to create one promise from several others -- its resolution value is an array of the promise results. Using it lets us remove a bunch of intermediary variables and simplify the code around promises as bit.
This is a follow-on to #672.

Use `Promises.zip` to simplify promise code

---

app/assets/data/swagger.yaml
app/jobs/import_versions_job.rb
app/models/version.rb
config/initializers/archiver.rb
db/migrate/20200216215324_add_length_and_media_type_to_versions.rb
db/schema.rb
lib/archiver/archiver.rb
lib/file_storage/local_file.rb
lib/file_storage/s3.rb
lib/tasks/data/20200218_add_version_length_media_type.rake
test/jobs/import_versions_job_test.rb
test/models/version_test.rb

This also includes a third field, `media_type_parameters`, which holds things like `charset=utf-8` that get tacked onto the end of the media type.
There is also a `content_type` getter/setter that includes the parameters, and sets `media_type` and `media_type_parameters` appropriately.
Fixes #199.
To do:

Add `content_length` & `media_type` to Version

---

lib/tasks/data/20200218_add_version_length_media_type.rake

The original version of the data migration that populated `content_length` and `media_type` from #669 worked fine on small databases, but not as well in production. It also didn't handle a few edge cases that existed in the actual database very well. This version lets you set a timeframe, has slightly clearer logging, handles situations where the original `Content-Type` header was invalid, and can load data from the stored response body if there's no good info in `source_metadata`.
**Still need to go over this with a fine-toothed comb before merging!** I’ve been running a smaller script to try and migrate the production database, and this is a port of all the changes I made. I haven’t actually run *this* actual rake script.

Improve the content_length/media_type migration

---

app/controllers/api/v0/pages_controller.rb

It turns out we were issuing a really overcomplicated query when calculating pagination information for `Page` objects -- we'd join to maintainers and tags even if we didn't need to do any filtering on them, causing a two-step query for the relevant page IDs, rather than one. This two-step query has been KILLING our database in production.
This only joins to those tables if we are actually filtering on them. It should drastically increase performance in our most common cases and not affect others.
This also flips from `eager_load` to `left_outer_joins` for this case. The `left_outer_joins` call used to be problematic, but no longer is. I think that’s because of how we split up the logic when we finally fetch the actual results, but may also be due to improvements in ActiveRecord between …

Perf: avoid unnecessary joins in pagination

---

app/controllers/api/v0/versions_controller.rb
app/jobs/analyze_change_job.rb

Now that versions actually have a real media type (see #669), we no longer need custom code to try and figure out a version’s media type. We can just ask for `version.media_type`.

Remove hacky code to detect version media type

---

.rubocop.yml
.rubocop_todo.yml
app/jobs/import_versions_job.rb
app/lib/data_helpers.rb
app/models/version.rb
lib/tasks/data/20200218_add_version_length_media_type.rake
test/jobs/import_versions_job_test.rb
test/models/version_test.rb

Version media types and media type parameter names (and the `charset` parameter value) are always normalized as lower-case when set because they are not actually case-sensitive. This makes any code that needs to use them much simpler, since it doesn't have to handle variations in case or spacing.
Fixes #689.

Ensure media type & parameters are lower-case

---

app/lib/data_helpers.rb
lib/tasks/data/20200218_add_version_length_media_type.rake

Without line endings, it's tough to stream logs (for example, we can't see the logs if we don't write line endings when running as a Kubernetes job). If running on a TTY, keep the friendly output that updates the line. On non-TTY interfaces, however, just write out the log as a line, and include a timestamp.

Don't rewrite lines in progress logs on non-TTYs

---

app/assets/data/swagger.yaml
app/jobs/analyze_change_job.rb
app/jobs/import_versions_job.rb
app/models/version.rb
db/migrate/20201112194523_remove_media_type_parameters_from_version.rb
db/schema.rb
lib/tasks/data/20200218_add_version_length_media_type.rake
test/jobs/import_versions_job_test.rb
test/models/version_test.rb

This removes the `Version#media_type_parameters` field (it wasn’t useful) and changes the `Versions#media_type` field to a cleaned-up, normalized, canonicalized field (instead of just reflecting whatever the HTTP response’s `Content-Type` header had). This makes it dramatically more useful without removing canonical information stored elsewhere.
Fixes #752.

Remove `media_type_parameters`

---

lib/tasks/data/clean_media_types.rake

Silence DB-level debug messages, and log each attempted change so you can see progress being made, regardless of whether any records wound up being changed.

Improve the logging for `data:clean_media_types`

---

app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/urls_controller.rb
app/jobs/import_versions_job.rb
app/models/concerns/taggable.rb
app/models/merged_page.rb
app/models/page.rb
app/models/page_url.rb
app/models/version.rb
config/initializers/active_record_extras.rb
config/routes.rb
db/migrate/20201116224426_add_page_url_model.rb
db/schema.rb
lib/tasks/data/20201116_add_page_urls.rake
lib/tasks/merge_pages.rake
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/urls_controller_test.rb
test/fixtures/page_urls.yml
test/jobs/import_versions_job_test.rb
test/models/page_test.rb
test/models/page_url_test.rb
test/models/version_test.rb

This adds support for multiple URLs per page. The `url` field directly on a `Page` should now be treated as the current canonical URL, but pages may also have any number of additional URLs associated with them. Page + URL combinations may have a timeframe (`>= PageUrl.start_time` and `< PageUrl.end_time`) describing when they are valid and a notes field that are meant to mostly carry anecdotal information. The timeframe does have one technical purpose: if two pages occupied the same URL, we prefer the most current when adding new versions.
Things that still need to happen here:
Fixes #492.

Add `PageUrl` model to describe pages with multiple URLs

---

app/controllers/api/v0/versions_controller.rb
config/routes.rb
test/controllers/api/v0/versions_controller_test.rb

This adds a new API route at `/api/v0/pages/:page_id/versions/sampled` that gets a "sampled" list of versions — that is, one version per sampling period. Right now, the sampling period is hard-coded to one day, but we might change that in the future. The main idea here is to give people a list of versions to look at, but reduce the amount of data in a useful way for pages that we capture extremely often (e.g. `https://epa.gov`/ gets many captures every day). For most use cases, we don't want to look more granularly than each day.
Basically, instead of getting a list of versions, this gets a list of objects like:
```js
{
time: "2022-01-01",
version_count: 3,
// A version object like we would get from /versions.
// This is the latest `different` version in the sample period
version: { ... } …
```

Add API route for sampled list of versions

---

Gemfile
Gemfile.lock
config/application.rb
config/initializers/sentry.rb

Sentry's "Raven" library has been deprecated and in maintentance mode for a long time. The newwer, full-featured, updated gem is "sentry_sdk". Fixes #837.

Upgrade from Raven to Sentry SDK

---

.circleci/config.yml
.env.example
test/controllers/api/v0/versions_controller_test.rb

Something somewhere is still accessing these old buckets. Maybe related to these old examples? These should be cleaned up regardless, though.

Remove deprecated buckets from tests/examples

---

app/controllers/api/v0/versions_controller.rb
test/controllers/api/v0/versions_controller_test.rb

In #946, I added a `/pages/:id/versions/sampled` endpoint that returns no more than one page per date. The goal was to reduce the number of queries and the amount of data transferred to load some pages that have a *lot* of snapshots. It turns out this didn't work well because it still paginated by the number of versions it was querying, which means it still required the exact same number of requests (d'oh!). (It *did* reduce the amount of data sent, but not by much after gzipping responses. It was still many megabytes for some pages.)
This changes the approach to paginate by date range instead, which should make a big difference. The code is pretty rough, but as long as it works, I plan to deploy so we can try it out with the bigger production data set.
Some remaining concerns:
- Times …

Paginate samples by date range

---

lib/tasks/copy_data.rake

This makes the `copy_data` task slightly more robust. I encountered this issue when the task crashed while working on #992 today.

Handle disconnected records in copy_data task

---

Gemfile
Gemfile.lock

This reverts the Redis upgrade to v5 in #1004, since Resque is not yet compatible with it.

Revert Redis upgrade from #1004

---

Gemfile
Gemfile.lock

OK, this time I ran the server in production mode locally to make sure nothing *else* was missing. Argh.

Add missing dependency on net-imap

---

Gemfile
Gemfile.lock

Dependabot opened a PR for this (#1028) but then promptly closed it. Not sure what went wrong there, so I’m redoing it manually.

Upgrade Sentry to v5.5.0

---

app/models/page.rb
test/models/page_test.rb

I've been doing a bunch of cleanup lately, and the fact that `Page#url_key` does not automatically update to reflect `Page#url` is a huge pain. There's no reason this shouldn't be automatic, so this makes it so.

Ensure `url_key` stays in sync with `url`

---

lib/tasks/data/20230119_remove_bad_versionista_titles.rake

It turns out we have some bad page titles from back when we got data from Versionista (discovered while working on #1061). When a page was missing a title, Versionista showed human-friendly text like "None", "No title available", etc. We incorrectly read these in as titles. This updates old version records from Versionista by replaces those titles with an empty string.
There may be additional strings we're missing here, but this is a big improvement (covers almost 32,000 records). Verified by looking for titles used across many versions, then sampling a few of the stored response bodies to make sure they didn't actually have these strings as literal titles.

Remove bad old Versionista titles

---

app/models/page.rb
app/models/version.rb
lib/tasks/data/20230119_reset_page_titles.rake
test/models/page_test.rb

If a new version is an error (e.g. a 404 status code because the page was removed), don't update the page record's title with the title from the error response. This also uses the filename component of the URL as a fallback title in case no versions with a parsed title can be found.
Fixes #751.
Fixes #468.
To-Do:

Only update the page title for non-error versions

---

app/models/page.rb
app/models/version.rb
test/models/page_test.rb

I messed up a bunch of page titles in #1061 because I overlooked the fact that `Version#sync_page_title` only functioned if called on the latest version. This fixes the issue by moving all the meaningful logic about where and when to grab a title to `Page#update_page_title` and changes `Version#sync_page_title` to just call that, but with an argument that tells it to only look forward from the version's capture time. That's not *exactly* the same behavior for the Version method, but gets us effectively the same result. This should also make the migration run faster.

Resetting page titles should consider old versions

---

db/migrate/20230124182815_add_compound_time_uuid_indexes_on_versions.rb
db/schema.rb

Before we can actually do range-based pagination in any usefully workable way, we need to have indexes in place that support it (partially because the primary key for versions is a UUID, which is unordered -- this wouldn't be such a big deal with bigint). These indexes will take a while to build, so it's good to get these in place ahead of time.
A future change will remove the old, non-compound indexes that will be redundant after these new ones finish building.
Addresses part of #571, and required before deploying #1066.

Add new indexes for range-based pagination

---

app/controllers/api/v0/versions_controller.rb
app/controllers/concerns/paging_concern.rb
app/models/version.rb
db/migrate/20230124184531_remove_simple_time_indexes_on_versions.rb
db/schema.rb
test/controllers/api/v0/versions_controller_test.rb

This is a *super rough* first cut at the logic for range-based pagination for versions (see #579). It’s ugly, problematic, and absolutely not mergeable as-is, but lets us test things out. Still needs:
*Update 2023-01-25: I’m not going to extend this to other endpoints. While it would be nice, the real priority right now is doing the minimum required for https://github.com/edgi-govdata-archiving/web-monitoring/issues/168*
The slow performance of offset-based pagination (when you get a batch of results with a query like `SELECT xyz FROM table OFFSET = n LIMIT = m`) is a serious problem on the the `versions` table (really any large table, but in practice it’s just `versions` for this app). This solves the problem by using range-based pagination (skipping to the place you want in the result …

Use range-based pagination for versions

---

.env.example
app/policies/api_policy.rb
config/application.rb

This starts the path toward #1069 by adding an environment variable `ALLOW_PUBLIC_VIEW` that determines whether you need to be logged in to have `view` permissions on API routes. For now, it defaults to false, but once we are comfortable that it's safe, we'll switch the default to true.

Add config for public read access

---

app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/api_controller.rb
app/controllers/api/v0/maintainers_controller.rb
app/controllers/api/v0/tags_controller.rb
app/controllers/api/v0/urls_controller.rb
app/controllers/api/v0/versions_controller.rb
test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/maintainers_controller_test.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/tags_controller_test.rb
test/controllers/api/v0/urls_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb
test/fixtures/users.yml
test/test_helper.rb

It turns out we were lazy about a lot of permissions in the API since we had a small set of users and nobody with `view` permissions didn't also have `annotate`. Now that we are enabling public access, that's a problem! This makes sure we're checking appropriate permissions in all the API controllers and actions.
This also does a little work to differentiate requests with no credentials and invalid credentials, which is important now that we are enabling public view access (no credentials is OK, invalid credentials is obviously an error, but needs an API-style response rather than the default authentication error handling). Devise doesn't provide anything that differentiates those, so we have to drop down to check some Warden data.
Found as part of auditing API access and options in …

Ensure permissions are correctly enforced

---

app/assets/data/swagger.yaml
app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/changes_controller.rb
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/versions_controller.rb
app/controllers/concerns/blocked_params_concern.rb
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb

Some parameters for the various `/versions` collections cause expensive queries, so they are disallowed for public, non-logged-in usage.
Solves part of #1070.

Block public access to some expensive parameters

---

app/assets/data/swagger.yaml

In #946 and #992, I added a route for sampling versions of a page (a better solution for most use cases than listing every version), but failed to include documentation. This adds a helpful description of the route.

Add documentation for page sample route

---

.env.example
config/application.rb

In #1071, we added support for public, unauthenticated users to have `view` permissions in the API and turned it on in staging. There haven’t been any major issues, so we are now switching the default from `false` to `true` (which will turn it on in production).

Turn on public viewing by default

---

app/assets/data/swagger.yaml
app/views/home/index.html.erb
config/routes.rb

Now that we have public `view` permission, this updates the documentation to reflect it by describing how and when to authenticate.
It also duplicates the two main authentication routes under the API namespace at `/api/v0/users/sign_in` and `/api/v0/users/session` — the fact that they were at the root has always been confusing and this also allows the interactive features in the docs page to work.

Improve authentication documentation

---

config/environments/production.rb

It turns out we weren't sending any caching headers for assets in production, so they weren't generally getting cached. This adds a 1-day cache for them (most assets are compiled and have hashes in the name, so could be cached forever, but some don't, e.g. `robots.txt`).

Add caching headers for production assets

---

db/migrate/20230209200733_change_int_to_bigint_for_primary_keys.rb
db/schema.rb

Integer primary keys can cause problems over time on big tables, and in general it's just better practice to use bigints instead. Some of our larger tables use UUIDs instead of ints, so this only upgrades the tables that used ints. (Practically speaking, none of these tables are really *likely* to overflow their primary key sequence, but better safe than sorry here, especially with technical maintainers offboarding.)
Fixes #1067.

Change int primary keys to bigint

---

app/jobs/analyze_change_job.rb
app/jobs/import_versions_job.rb
test/jobs/import_versions_job_test.rb

We've disabled `AnalyzeChangeJob` via configuration in production. Since we also expect to never make use of it again, I've added a note in the code (I opted not to delete it in case it needs to get turned on in the future -- someone could always go get it back from the git history, but since there is no technical maintainer to replace me, I'm worried that's too big of a barrier.)
Fixes #1090.

Add disabled notice to AnalyzeChangeJob

---

.github/workflows/release.yml

To make releases a little simpler, you can now trigger them via a button in the GitHub Actions UI.

Add manually triggered workflow for releases

---

app/controllers/api/v0/diff_controller.rb

This is part of web-monitoring#168 — the goal here is to make our diff cache less important so we can shrink it or even remove it (in favor of just having CloudFront do the job).
CloudFront needs a `Date` header to go with the `Last-Modified` and `ETag` headers from the `stale?` method, and works better still if we give it an actual cache age. This adds the `expires_in` helper which sets all the headers. I've also taken the strategy of setting a *relatively* short cache time but a much longer revalidation window when a stale response can be used, to balance concerns about updating the diff algorithm and effective long-term caching.

Output CloudFront-friendly headers for diffs

---

.env.example
app/controllers/api/v0/annotations_controller.rb
app/controllers/api/v0/imports_controller.rb
app/controllers/api/v0/maintainers_controller.rb
app/controllers/api/v0/tags_controller.rb
app/controllers/api/v0/urls_controller.rb
app/controllers/api/v0/versions_controller.rb
config/application.rb
lib/api/api.rb
test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/imports_controller_test.rb
test/controllers/api/v0/maintainers_controller_test.rb
test/controllers/api/v0/tags_controller_test.rb
test/controllers/api/v0/urls_controller_test.rb
test/test_helper.rb

This adds an `API_READ_ONLY` environment variable, which blocks API operations that create/update/delete versions, annotations, etc. when set to `"true"`. Since we ware now working towards shutting down the entire system, this is helpful so we can work on creating archival data without worrying about the database changing from underneath us. See edgi-govdata-archiving/web-monitoring#170.

Add read-only mode to DB server

---

app/models/page.rb
lib/tasks/update_page_statuses.rake
test/models/page_test.rb

Pages have a `status` attribute that is meant to be a convenient way to figure out what the current status of a page is, skipping over short-lived, erroneous errors from a single snapshot. A while back, we added "effective" status codes to versions, which attempt to figure out if a version with a 200 status code actually should have been an error code (surprisingly common!). We should have updated Page's status calculation to use that, since the page is really about what is effectively the current state, but missed it at the time.
Even though this project is effectively dormant and being shut down, I’m adding this in to help make sure we get more useful archival data out as part of edgi-govdata-archiving/web-monitoring#170.

Use effective_status for Page#status

---

.circleci/config.yml

This just makes our CI reporting a little clearer when there are failures.

Split linting from testing in CI

---

app/assets/config/manifest.js

The last release seems to be running into some issues with Sprockets failing to recognize the `swagger.yml` file (even though it successfully precompiles). In Sprockets 4 there were changes to how config options are handled vs. what's in the `manifest.js` file, so I'm adding it to `manifest.js` to see if that solves it.

Link `data` directory in Sprockets manifest

---

app/models/invitation.rb
config/environments/production.rb

This fixes a few issues with user invitations/registration. The expiration date on an invitation somehow wound up being calculated based on N *seconds* instead of *days* from the current time!
~This also disables user e-mail confirmation for now. We’ve got some issues with Postmark that I *think* are on their end (I have a support ticket open with them), so it’s better not to require any e-mail to get an account set up for now. (Confirmation was always a weird step since invitations are currently required here; it was originally intended for a future vision where we wouldn’t require invitations, but that future will probably never exist for this codebase.)~

Fix e-mail invitation expiration and confirmation issues

---

app/controllers/api/v0/versions_controller.rb
app/models/version.rb
app/views/api/v0/versions/network_error.html.erb
db/migrate/20250202234940_add_network_error_to_versions.rb
db/schema.rb
test/controllers/api/v0/versions_controller_test.rb

This gives us a way to model the server itself being down instead of responding with an HTTP 4xx or 5xx error. In the very early times (when this DB was focused around data from Versionista and Pagefreezer), we shoved errors and HTTP statuses in `source_metadata` because we often didn't have a clear representation of different kinds of errors. We later switched to 100% Internet Archive as a source, and didn't consider the fact that they don't track network-level errors since we were no longer seeing whole hostnames disappear at that point. Now at the start of 2025, we're seeing a lot of servers simply being shut down, and need to be able to clearly represent that.
For captures of network-level failures (i.e. no HTTP response message was received), we can record a version with:
- `body_url …

Add `network_error` field to Version model

---

config/initializers/archiver.rb
config/initializers/file_storage.rb
lib/file_storage/s3.rb
test/lib/file_storage/s3_test.rb

This adds the ability to handle data in S3 that is gzipped. It also sets things up to automatically gzip anything we put in S3 to save space.

Handle gzipped data in S3

---

app/controllers/api/v0/diff_controller.rb
config/initializers/routing.rb
lib/differ/simple_diff.rb
test/fixtures/changes.yml
test/fixtures/versions.yml
test/lib/differ/simple_diff_test.rb

In #1184, we added a nice HTML representation for versions that were network errors instead of HTTP responses. But the differ routed around that and instead returned an error because there was no content to diff. This updates the differ to use the nice new HTML page for network errors.
That is, we are currently seeing diff results like:
And we want to see an actual diff instead of an error.

Route differ to fake content for network errors

---

app/models/page.rb
app/models/version.rb

In #1184, I added the ability to track versions that represent network errors instead of valid HTTP reponses. I forgot about calculating the page's effective status, though, where these versions were getting ignored (since they have nil status). Ideally, I think we'd set a status of `0`, but there are some validations that disallow that and other places I need to be careful of causing problems. So the easiest thing for now is to treat a network error as a 404. Close enough to do the job.

Ensure network errors get counted for page status

---

lib/file_storage/s3.rb
test/lib/file_storage/s3_test.rb

In #1185, we added support for reading and writing gzipped data to S3. Unfortunately, the support only worked when writing a *string*, but not when writing an IO stream. It turns out that when saving a batched import to execute in a job, we write a stream. Oops.

Fix gzip writing bug introduced in #1185

---

app/jobs/import_versions_job.rb
test/jobs/import_versions_job_test.rb

Several years back, we changed the version import logic to matche the changing (and more HTTP response-like) fields for `Version`. When doing so, we attempted to be backwards compatible with the old import format. It turns out that didn't quite work with the `page_url` field, though! The cleanup/upgrade came too late in the process, and a different part of the code was still requiring `page_url` when it should have required `url`. This fixes the issue.
This still leaves some of the format upgrade/normalization logic in place, but I am currently updating the only import script left (finally) to use the new format, so I *should* come back around and clean this all up later this week.

Fix import format upgrade logic

---

lib/api/api.rb
lib/archiver/archiver.rb

While debugging some import issues this week, I realized it would have been *very* helpful to know what hash we actually got when trying to archive content, not just what hash we expected. This adds it to the error message.

Add more detail to `MismatchedHashError`

---

Dockerfile

In v3.4.2, the official Ruby Docker image dropped libyaml. However, we need it, so we need to add it to our Dockerfile. This also fixes some casing on syntax that Docker has recently started complaining about.
This is a follow-on to #1195.

Add `libyaml` to Dockerfile

---

.circleci/config.yml

We previously only built the Docker images for this project as part of the release process (because building and publishing were integrated). That recently led to an issue where a subtle change to our base image between versions caused a release to fail. This ensures we build the Docker images whenever we run tests so we get a heads-up on issues like this.
This is a follow on to #1195.

Build Docker images as part of normal CI

---

app/models/page.rb
app/models/page_url.rb
lib/tasks/data/renormalize_urls.rake
test/jobs/import_versions_job_test.rb
test/models/page_test.rb

We've had a bunch small issues lately with multiple pages and other oddball matching issues because the way we normalize URLs is not expansive enough and not totally consistent between `Page` and `PageUrl`(!). This takes a more serious crack at normalization and also switches to Rails's new(ish) normalization tooling so we can clean up a lot of call-sites because normalization now Just Happens™ at the right times.
Ideally we could lean on Addressable or Surt for a real robust normalization algorithm, but Addressable requires more careful investigation (it would alter over 1,000 of our URLs in ways that are probably correct but I am 100% confident about) and Surt turns out to need some more work in order to be safe (see #1215 for more). So for now we have our own custom normalization.
This …

Do a better job normalizing URLs

---

app/lib/surt.rb
app/models/version.rb

We now how have `effective_status` routines for versions in two places: this codebase and the web-monitoring-task sheets project (https://github.com/edgi-govdata-archiving/web-monitoring-task-sheets/blob/841016    4460eb4e970b93ea947af5d70e57768b22/analyst_sheets/analyze.py#L320-L392). This updates the two implementations to match.
Fixes #1193, #1200.

Update `effective_status` to match task sheets

---

app/jobs/import_versions_job.rb
app/lib/data_helpers.rb
app/models/version.rb
lib/tasks/data/20250330_downcase_header_names.rake
test/jobs/import_versions_job_test.rb
test/models/version_test.rb

HTTP headers names are not case-sensitive, so normalize the keys on `Version.headers` to be lower-case strings to simplify usage. This also drops some long-deprecated import format handling where headers were part of `source_metadata`.
Includes a data migration task to normalize all *existing* headers in version records. Future updates will automatically be normalized by the new code.
Fixes #1194.

Normalize version header names to lower-case

---

lib/tasks/data/20250330_downcase_header_names.rake

The current version of the data migration is going pretty slow! This runs *much* faster. I had been hoping the new batched query support in the current version of Rails would solve this well enough for us, but it doesn’t.

Massive speedup for downcased headers migration

---

lib/tasks/data/20250330_downcase_header_names.rake

Pretty minor, but helpful speed-bump. This is already going at an ETA of < 24 hours compared to the old AR batched finder approach that had a 40 day ETA.

Additional optimization on header migration

---

app/assets/data/swagger.yaml
app/controllers/api/v0/pages_controller.rb
app/controllers/api/v0/versions_controller.rb
app/models/page.rb
app/models/page_url.rb
app/models/version.rb
lib/tasks/analyze_changes.rake
lib/tasks/copy_data.rake
test/controllers/api/v0/pages_controller_test.rb
test/controllers/api/v0/versions_controller_test.rb

This covers part 1 of #1208 and generally removes support for the `different` query param, which doesn't behave like you would probably expect and regularly causes problems. It was designed in a world where we expected to have such frequent and continuous captures of pages that any time we had a "different" version, we knew it had *just* changed. The reality is that you can never get captures frequent enough to do that even in practical terms, and in theoretical terms it's just wrong. We've long since switched to always querying in a way that removes checking the `different` field, and it's past time to remove it from the API.
This leaves it in place in ONE spot of the API, which does not return an actual list of versions and thus does not have the same problems: `GET …

Drop support for `?different` query param

---

app/assets/data/swagger.yaml

I forgot to update these when I added `network_error`, but it looks like there have been a *lot* of updates and changes that have not hit these docs. This updates the fields in the `Page` and `Version` models, although there is still more that's not quite up-to-date here, I think.

Update Swagger docs for `Version` and `Page`

---

Gemfile.lock

Fixes a security vulnerability. Dependabot should have created a PR for this, but something seems broken — its logs show that it *think* it made a PR, even though it did not.

Upgrade Nokogiri to v1.18.9

---

test/controllers/api/v0/annotations_controller_test.rb
test/controllers/api/v0/urls_controller_test.rb

The IETF revised the name of status code 422 to "Unprocessable Content" and Rack also renamed the symbol used for the same status code. The previous symbol (`:unprocessable_entity`) has been deprecated and now logs lots of warnings. This fixes all the uses of it in our code, although we still get warnings from within Rails and WebMock.

Fix warnings about deprecated `:unprocessable_entity`
