edgi-govdata-archiving/web-monitoring-db

- Gemfile
- Gemfile.lock
- README.md
- config/newrelic.yml
Should've done this a while ago!
> Add New Relic monitoring

- README.md
Add a nice welcoming header to the README for Global Sprinters!
> Add Global Sprint header to README

- README.md
> revert global sprint

- README.md
> ReadMe file lacks instructions for postgres - second take

- .env.example
Forgot side by side text in previous PR
> Add missed env var.

- app/controllers/api/v0/annotations_controller.rb
- app/controllers/api/v0/api_controller.rb
- app/controllers/api/v0/changes_controller.rb
- app/models/annotation.rb
- app/models/change.rb
- db/migrate/20170713234650_set_change_priority_default_to_null.rb
- db/migrate/20170717072416_add_significance_to_change.rb
- db/schema.rb
- swagger.yaml
- test/controllers/api/v0/annotations_controller_test.rb
- test/controllers/api/v0/changes_controller_test.rb
- test/fixtures/changes.yml
- test/models/change_test.rb
~**Work in progress; DO NOT MERGE**~
This is tracking the work for resolving #102, which is a general cleanup of `priority`, `significance` and how those fields get set. Discussion in the issue is not entirely resolved yet, so this will get worked on as discussion evolves there.
> Change priority/significance cleanup

- swagger.yaml
> Document `capture_time` query for pages

- app/controllers/api/v0/annotations_controller.rb
- app/controllers/api/v0/changes_controller.rb
- app/controllers/api/v0/pages_controller.rb
- app/controllers/api/v0/versions_controller.rb
- app/controllers/concerns/paging_concern.rb
- swagger.yaml
- test/controllers/api/v0/pages_controller_test.rb
> Rename pagination parameter to 'chunk' and add 'chunk_size' knob.

- README.md
Also alphabetize the contributors list so it doesn’t seem like a game of favorites.
@maxtedford I totally forgot to ask you to add yourself in your PR! Let me know if this is OK or if you’d like to be mentioned/linked to differently (or not at all).
> Celebrate contributions from @maxtedford!

- .env.example
At some point we discussed adding this to ``.env.example``. I don't think
we came to a clear conclusion, but it seems reasonable to me to add it.
> Add EDGI S3 domains to ALLOWED_ARCHIVE_HOSTS.

- Gemfile
- Gemfile.lock
- app/controllers/api/v0/api_controller.rb
- app/controllers/concerns/paging_concern.rb
- app/controllers/concerns/same_origin_sessions_concern.rb
- app/jobs/import_versions_job.rb
- lib/jwt_tools/jwt_coder.rb
Upgrade Rubocop and fix new errors it added. Been meaning to take care of this since #141.
> Upgrade Rubocop to v0.50.0

- lib/tasks/rename_site.rake
This is necessary for #145. Note it will have to be updated when someone tackles #24.
> Add rake task to rename a site

- app/jobs/import_versions_job.rb
- test/jobs/import_versions_job_test.rb
Better error-reporting would have useful when writing edgi-govdata-archiving/web-monitoring-processing#114. Improving error messages in case it comes up again.
> Add some more helpful errors

- app/controllers/api/v0/versions_controller.rb
- app/models/version.rb
- test/models/version_test.rb
This closes #164
@edgi-govdata-archiving/lieutenants
> Add next link to VersionsController#show

- README.md
- app/controllers/api/v0/annotations_controller.rb
- app/controllers/api/v0/changes_controller.rb
- app/controllers/api/v0/pages_controller.rb
- app/controllers/api/v0/versions_controller.rb
- test/controllers/api/v0/annotations_controller_test.rb
- test/controllers/api/v0/changes_controller_test.rb
- test/controllers/api/v0/pages_controller_test.rb
- test/controllers/api/v0/versions_controller_test.rb
This is for #150
@Mr0grog Please review and let me know if everything is correct and if this patch complies with code styling/convention.
> Meta section with count of results

- README.md
@danielballan is this what you were thinking of for `citext`?
> Add `citext` postgres extension to README

- docs/issue_template.md
> adding template for new issues

- .circleci/config.yml
Try to get Circle to auto-publish our Docker images whenever merging into master.
Gonna merge this pretty much straightaway because not really sure how else to test.
> Auto publish docker from circle

- db/seeds.rb
For issue  #158. All manual testing.
> Add prompt for seeding database without archive hosts

- app/controllers/api/v0/imports_controller.rb
- app/controllers/api/v0/pages_controller.rb
- app/controllers/api/v0/versions_controller.rb
- app/jobs/import_versions_job.rb
- app/models/page.rb
- app/models/version.rb
- db/migrate/20180415065623_add_different_to_versions.rb
- db/migrate/20180418061850_add_skip_unchanged_versions_to_imports.rb
- db/schema.rb
- swagger.yaml
- test/controllers/api/v0/imports_controller_test.rb
- test/controllers/api/v0/pages_controller_test.rb
- test/controllers/api/v0/versions_controller_test.rb
- test/models/version_test.rb
I guess it’s not like they really conflict.
Fixes #266 ALL THE WAYS
> Or, you know, just do all the approaches for #266

- app/controllers/healthcheck_controller.rb
- config/routes.rb
- test/controllers/healthcheck_controller_test.rb
> Add a basic /healthcheck endpoint with test.

- .circleci/config.yml
This is a follow-on to #410 based on @danielballan's comment: https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/410#discussion_r224223704
> Run tests on commits/pushes to `master`

- lib/tasks/copy_data.rake
Since we wrote this rake task, we've made changes to the API (added maintainers and tags, removed versions from the page endpoint). We haven't updated this task to match, though, and so it always fails. This makes some sorely needed updates.
I’ve had a rough version of this sitting in my working copy for a while, and it’s high time I cleaned it up so this task is usable for others.
> Update `copy_page` rake task to match current API

- .github/stale.yml
Per https://github.com/edgi-govdata-archiving/overview/issues/231
> Remove `idea` as exempt label

- db/seeds.rb
fix seed.rb build process where 'admin' role is now managed in permissions property
> fix seed.rb build 

- .env.example
I had to create a new private key for JWT tokens, and kept generating it in the wrong format and having problems! This adds some simple instructions for generating a new key to the `.env.example` file (in case you forget like me).
> Describe how to generate a new `TOKEN_PRIVATE_KEY`

- README.md
- app/models/page.rb
- test/models/page_test.rb
> Add news tag to pages with news, press, blog in a url

- .circleci/config.yml
- .rubocop.yml
- bin/lint
- bin/rails
- bin/rake
- bin/update
- bin/yarn
This should help speed up running the Rubocop linter.
> Speed up Rubocop

- Gemfile
- Gemfile.lock
- app/jobs/analyze_change_job.rb
- test/jobs/analyze_change_job_test.rb
Uses Concurrent Ruby's Promises: https://github.com/ruby-concurrency/concurrent-ruby/blob/master/docs-source/promises.in.md
Closes #420
> Run AnalyzeChangeJob’s diffs in parallel

- lib/tasks/data/clean_media_types.rake
This was supposed to be part of #778, but I forgot to commit the file!
> Add task for cleaning up `Version#media_type`

- lib/tasks/copy_data.rake
I needed this to test some recent issues.
> Add ability to copy changes from another DB

- .circleci/config.yml
See https://circleci.com/blog/ubuntu-14-16-image-deprecation
> Remove deprecated `machine: true` CircleCI syntax

- Gemfile
- Gemfile.lock
> Add missing net-pop gem for production

- .circleci/config.yml
This updates from a deprecated Docker image for Postgres, but I also need to figure out what went wrong on the main branch here, since tests are failing in CI (maybe because of this? but not likely) but not locally. :(
> Clean up CircleCI

- .circleci/config.yml
- .github/workflows/release.yml
Fix some bugs with the new push-button release workflow.
> Release workflow no work yet

- README.md
Note the non-maintained status of this project. Part of edgi-govdata-archiving/web-monitoring#168.
> Add maintenance notice to README

- README.md
- app/assets/data/swagger.yaml
Fixes #1204 (or at least the html_text and html_source elements)
> Fix incorrect diff_types in swagger docs

- app/controllers/api/v0/diff_controller.rb
- app/controllers/application_controller.rb
We used to use `stale?` to avoid re-computing diffs when possible, but if we raised an error afterward (during diffing), we would wind up with some fairly extreme caching headers getting sent out with the error! The occasional diff failure would then be stuck in CloudFront a very long time.
`stale?` sets a lot of different caching mechanisms when it's called and doesn't give you an easy way to roll them back. This solves the issue by creating a `when_stale()` method that takes a block. It keeps track of the original header values and resets them if the block raises an error instead of returning a useful value, that way an error handling code can safely set (or not set) cache without worrying about what other cache features have already been messed with.
This also moves some of the more …
> Try not to cache diff errors in CDN
